all:
	@make -C ex00
	@make -C ex01
	@make -C ex02
	@make -C ex03

re:
	@make -C ex00 re
	@make -C ex01 re
	@make -C ex02 re
	@make -C ex03 re

fclean:
	@make -C ex00 fclean
	@make -C ex01 fclean
	@make -C ex02 fclean
	@make -C ex03 fclean